import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer, Slide } from "react-toastify";
import { UserProvider } from "@/lib/UserProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        <UserProvider>
          {children}
        </UserProvider>

        <ToastContainer
          hideProgressBar
          transition={Slide}
          position="top-right"
          autoClose={2000}
        />
      </body>
    </html>
  );
}
